#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  profiles : dev
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/project_boot?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 5
    maxActive: 20
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxWait: 60000
    # open PSCache
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    filters: stat,wall,log4j2
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


mybatis:
  type-aliases-package: com.sunyu.curator
  mapper-locations: classpath*:mappers/*.xml
  configuration:
     log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
     map-underscore-to-camel-case: true
     cache-enabled: true

curator:
  connectString: 127.0.0.1:2181
  connectionTimeoutMs: 5000
  elapsedTimeMs: 5000
  retryCount: 5
  sessionTimeoutMs: 60000
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: ../logs
  error:
    whitelabel:
      enabled: false