#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  profiles : dev
  kafka:
    bootstrap-servers: 10.236.64.81:9020,10.236.64.82:9020,10.236.64.83:9020,10.236.64.84:9020
    consumer:
      group-id: mygroup
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 100
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
kafka:
  consumer:
    topics: k8s_app
  producer:
    topics: k8s_app
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: ../logs
  error:
    whitelabel:
      enabled: false