#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  profiles : dev
  lifecycle:
    timeout-per-shutdown-phase: 30
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: ../logs
  error:
    whitelabel:
      enabled: false
  shutdown: graceful